name             'martinb3-base'
maintainer       'Martin Smith'
maintainer_email 'martin@mbs3.org'
license          'Apache 2'
description      'Installs/Configures base'
long_description 'Installs/Configures default for my personal servers'
version          '0.1.0'

depends 'user'
depends 'motd-tail'
depends 'apt'
depends 'auto-patch'
depends 'chef-client'
depends 'chef-sugar'
depends 'client-rekey'
depends 'newrelic'
depends 'ntp'
depends 'ohai'
depends 'omnibus_updater'
depends 'openssh'
depends 'postfix'
depends 'iptables'
depends 'rsyslog'
depends 'sudo'
depends 'timezone-ii'
depends 'yum'
depends 'fail2ban'
